# Generated by Django 2.2.12 on 2023-02-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.TextField()),
                ('about_detail', models.TextField()),
                ('about_img', models.ImageField(blank=True, upload_to='about')),
            ],
        ),
    ]
