# Generated by Django 2.2.12 on 2023-02-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(blank=True, upload_to='service')),
                ('service_title', models.CharField(max_length=50)),
                ('service_detail', models.TextField()),
            ],
        ),
    ]
