# Generated by Django 2.2.12 on 2023-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_mobile', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_open_hour', models.TextField()),
            ],
        ),
    ]
