# Generated by Django 2.2.12 on 2023-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_title_main',
            field=models.CharField(default='', max_length=100),
        ),
    ]
