# Generated by Django 2.2.12 on 2023-02-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_service_service_title_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_title_main',
        ),
    ]
