# Generated by Django 2.2.12 on 2023-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_service_service_title_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
