# Generated by Django 2.2.12 on 2023-02-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_contact_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(default='perfectsolution@outlook.com', max_length=50),
        ),
    ]
