# Generated by Django 2.2.12 on 2023-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230213_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_img',
            field=models.ImageField(blank=True, default='hero/hero-img.png', upload_to='hero'),
        ),
    ]
