# Generated by Django 2.2.12 on 2023-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230213_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_img', models.ImageField(upload_to='our_values')),
                ('value_title', models.CharField(max_length=30)),
                ('value_detail', models.TextField()),
            ],
        ),
    ]
