# Generated by Django 2.2.12 on 2023-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_ourvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurValueTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title_main', models.CharField(max_length=50)),
            ],
        ),
    ]
